[package]
name = "fenris-geometry"
version = "0.0.3"
authors = ["Andreas Longva <longva@cs.rwth-aachen.de>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/InteractiveComputerGraphics/fenris"
description = "Geometry functionality for fenris"
edition = "2021"

[dependencies]
itertools = "0.9"
nalgebra = "0.30"
serde = { version="1.0", features = [ "derive" ] }
numeric_literals = "0.2.0"
fenris-nested-vec = { version = "0.0.1", path="../fenris-nested-vec" }
proptest = { version="1.0", optional = true }

[dev-dependencies]
matrixcompare = "0.3"
util = { path="../util" }
